### ISSUE TITLE
SQL statement are twice in the PostGIS SQL file

### ISSUE THREAD

**Issue by yjacolin** [GraceTHD-community/GraceTHD-MCD#1]
See https://github.com/GraceTHD-community/GraceTHD-MCD/blob/master/sql_postgis/gracethd_3_tables.sql#L754

which seems exactly the same as the first line at the top of the file.

**Comment by zzzef** [comment]
Hello Yves, 

Right. v2-RC1 is coming this week. 
Thank you.
